// angular/src/app/features/public/events/events/events.component.ts
import {Component, Inject, PLATFORM_ID} from '@angular/core';
import {Observable, of} from 'rxjs';
import {RecSysPreviewI} from '@ingenium/app/shared/models/item/recsysI';
import {EventService} from "@ingenium/app/core/services/coreAPI/item/derived_services/event.service";
import {HttpState} from "@ingenium/app/shared/models/httpState";
import {isPlatformBrowser} from "@angular/common";

@Component({
  selector: 'app-page',
  templateUrl: './events.component.html',
  styleUrls: ['./events.component.scss']
})
export class EventsComponent {
  events$: Observable<HttpState<RecSysPreviewI[]>> = of({loading: true, data: [], error: null});

  constructor(@Inject(PLATFORM_ID) platformId: any, eventService: EventService) {
    if (isPlatformBrowser(platformId)) {
      this.events$ = eventService.getEventsList();
    }
  }
}

<header>
  <app-layout-public-header [light_theme]="true" />
</header>

<main class="ingenium-container relative" id="main-content">
  <h1 class="white-section-title white-section-title-blue white-section-title-large">Evenementen</h1>
  <p>TD's en andere evenementen kan je op deze pagina vinden.</p>

  @let events = this.events$ | async;
  @if (events && (events.loading || events.error)) {
    <app-loading-indicator [isLoading]="events.loading" [isErrored]="events.error !== null"
                           [title]="'Evenementen aan het laden'" [message]="'Evenementen worden opgehaald'" />
  } @else if (events && (events.data?.length ?? 0) > 0) {
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
      @for (event of events.data; track event.name) {
        <app-rec-sys-item-preview [recsysItem]="event" />
      }
    </div>
  } @else {
    <div class="alert alert-info alert-border">
      <p class="text-sm text-blue-700">Er staat momenteel geen evenementen online</p>
    </div>
  }
</main>

// sveltekit/src/routes/events/+page.svelte
<script lang="ts">
  import type { PageProps } from './$types';
  import Header from '$lib/components/layout/header.svelte';
  import RecSysPreviewItem from '$lib/components/recsys/rec-sys-preview-item.svelte';

  let { data }: PageProps = $props();
</script>

<svelte:head>
  <title>Events | Ingenium UA</title>
</svelte:head>

<header>
  <Header whiteTheme={true} />
</header>

<main class="ingenium-container relative" id="main-content">
  <h1 class="white-section-title white-section-title-blue white-section-title-large">Evenementen</h1>
  <p>TD's en andere evenementen kan je op deze pagina vinden.</p>

  {#if (Array.isArray(data.events) && data.events.length > 0)}
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
      {#each data.events as item}
        <RecSysPreviewItem {item} />
      {/each}
    </div>
  {:else}
    <div class="alert alert-info alert-border">
      <p class="text-sm text-blue-700">Er staat momenteel geen evenementen online</p>
    </div>
  {/if}
</main>
