// src/app/features/public/info/credits/credits.component.ts
import { Component } from '@angular/core';
import {apiEnviroment} from "@ingenium/environments/environment";

@Component({
  selector: 'app-page',
  templateUrl: './credits.component.html',
  styleUrls: ['./credits.component.scss']
})
export class CreditsComponent {
  revision: string = apiEnviroment.versions.revision;
}

<header><app-layout-public-header [light_theme]="true" /></header>

<main class="ingenium-container">
  <h1 class="white-section-title white-section-title-blue">Credits</h1>
  <p>Our website was not made in a few minutes, it required the hard work of a lot of people. This page serves as a thank you to all the people who contributed to the creation of this website.</p>

  <div class="grid grid-cols-1 md:grid-cols-2 gap-4 text-gray-700">
    <div>
      <p class="font-bold text-black">List of students</p>
      <ul class="list-disc list-inside">
        <li>Robbe De Helt</li>
        <li>Yorben Joosen</li>
        <li>Inias De Belder</li>
        <li>Sigfried Seldeslachts</li>
        <li>Wout De Smit</li>
        <li>Bas Calders</li>
        <li>Nicolas Grupping</li>
      </ul>
    </div>
    <div>
      <p class="font-bold text-black">Others</p>
      <ul class="list-disc list-inside">
        <li><a (click)="gotoPage('sub/info/licences')" class="cursor-pointer">3rd party licenses</a></li>
        <li>Revision: {{ revision }}</li>
      </ul>
    </div>
  </div>
</main>

// sveltekit/src/routes/info/credits/+page.svelte
<script lang="ts">
  import Header from '$lib/components/layout/header.svelte';
</script>

<header>
  <Header whiteTheme={true} />
</header>

<main class="ingenium-container" id="main-content">
  <h1 class="white-section-title white-section-title-blue">Credits</h1>
  <p>Our website was not made in a few minutes, it required the hard work of a lot of people. This page serves as a thank you to all the people who contributed to the creation of this website.</p>

  <div class="grid grid-cols-1 md:grid-cols-2 gap-4 text-gray-700">
    <div>
      <p class="font-bold text-black">List of students</p>
      <ul class="list-disc list-inside">
        <li>Robbe De Helt</li>
        <li>Yorben Joosen</li>
        <li>Inias De Belder</li>
        <li>Sigfried Seldeslachts</li>
        <li>Bas Calders</li>
        <li>Nicolas Grupping</li>
        <li>Wout De Smit</li>
      </ul>
    </div>
    <div>
      <p class="font-bold text-black">Others</p>
      <ul class="list-disc list-inside">
        <li>Revision: ????</li>
      </ul>
    </div>
  </div>
</main>
